### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by kevando** [michaelcontento/redux-storage-engine-reactnativeasyncstorage#4]
Would it be possible to see a sample of code using this? I think this will be super helpful to my app, but I am very new to redux.

**Comment by michaelcontento** [comment]
Hi, have you looked at the readme of [redux-storage](https://github.com/michaelcontento/redux-storage)? 

`redux-storage` is the main library and this is just one engine that can be used with it. So the README of `redux-storage` should answer more questions :smile:
